app/Bet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class Bet extends Model
{
	protected $fillable = ['fecha_registro', 'fecha', 'usuario', 'compuesta', 'monto', 'ganancia', 'status', 'web', 'bonus', 'exchange_id',];

	public $timestamps = false;

	protected $appends = ['exchanged_amount', 'exchanged_profit',];

	//Relationship

	public function bets_detail()
	{
		return $this->hasMany(BetsDetail::class, 'idbets');
	}

	public function user()
	{
		return $this->belongsTo(User::class, 'usuario');
	}

	public function stsbets()
	{
		return $this->belongsTo(Stsbet::class, 'status');
	}

	public function corredorComision()
	{
		return $this->belongsTo(CorredorComision::class, 'usuario', 'idusuario');
	}

	//Attributes
	public function getComisionAttribute()
	{

		if (!$this->is_corredor || $this->monto == 0) {
			return 0;
		}

		$comision = $this->monto * $this->percentage / 100;

		return $comision;
	}

	public function getPercentageAttribute()
	{
		if ($this->monto > 0 && $this->user->corredor) {
			$percentage = (($this->ganancia - $this->monto) * 100) / $this->monto;
			$comision = $this->corredorComision->where('idusuario', $this->usuario)->with(['comision' =>
			function ($query) use ($percentage) {
				$query->where('desde', '<=', $percentage)->where('hasta', '>=', $percentage);
			}])->get()->all();

			return $comision[0]->comision[0]->comision;
		}
		return 0;
	}

	public function getDateAttribute()
	{
		$date = date_create($this->fecha);
		return date_format($date, "d-m-Y");
	}

	public function getUserNameAttribute()
	{
		return $this->user->name;
	}

	public function getStatusNameAttribute()
	{
		return $this->stsbets->nombre;
	}

	public function getIsCorredorAttribute()
	{
		$user = User::find($this->usuario);

		return $user->corredor;
	}

	public function getHumanAmountAttribute()
	{
		return number_format($this->monto, 2);
	}

	public function getHumanProfitAttribute()
	{
		return number_format($this->ganancia, 2);
	}

	public function getBadgeAttribute()
	{
		$classBadge = 'badge-default';
		if (in_array($this->status, ['2', '5']))
			$classBadge = 'badge-success';
		elseif ($this->status == 3)
			$classBadge = 'badge-important';
		elseif ($this->status == 4)
			$classBadge = 'badge-warning';

		return $classBadge;
	}

	public function getIsWinnerAttribute()
	{
		$win = 0;

		foreach ($this->bets_detail as $detail) {
			$win += intval($detail->games_probs->acierto);
		}

		$count = $this->bets_detail->count();
		return $count == $win;
	}

	public function getIsLoseAttribute()
	{
		$lose = 0;
		foreach ($this->bets_detail as $detail) {
			$lose += $detail->is_game_over && $detail->games_probs->acierto == 0 ? 1 : 0;
		}

		return $lose > 0;
	}

	public function getIsCompletedAttribute()
	{
		$result = 0;

		foreach ($this->bets_detail as $detail) {
			$result += $detail->games_probs->game->resultado->count()
				|| in_array($detail->games_probs->game->status, [2, 3]) ? 1 : 0;
		}
		$count = $this->bets_detail->count();

		return $count == $result;
	}

	public function getProfitAttribute()
	{
		$total = 0;
		foreach ($this->bets_detail as $key => $detail) {
			$key == 0
				? $total += $this->monto * $detail->games_probs->probabilidad
				: $total = $total * $detail->games_probs->probabilidad;
		}

		return $total;
	}


	public function getGanancia2Attribute()
	{
		return $this->calculeProfit();
	}

	public function getExchangedAmountAttribute()
	{
		$user = User::find($this->usuario);
		$currency = Currency::find($user->currency_id);

		if($currency->default) {
			return $this->monto;
		}

		return exchangeDefault($this->monto, $currency->id);	
	}

	public function getExchangedProfitAttribute()
	{
		$user = User::find($this->usuario);
		$currency = Currency::find($user->currency_id);

		if($currency->default) {
			return $this->ganancia;
		}

		return exchangeDefault($this->ganancia, $currency->id);	
	}

	//Scopes

	public function scopeTicketId($query, $id)
	{
		if ($id != "")
			$query->where('id', 'LIKE', "%$id%");
	}

	public function scopeId($query, $id)
	{
		if ($id != "" and is_numeric($id))
			$query->where('id', $id);
	}

	public function scopeUserName($query, $name)
	{
		if ($name != "" and !is_numeric($name)) {
			$users = User::where('name', 'LIKE', "%$name%")->get();

			$query->whereIn('usuario', $users->pluck('id'));
		}
	}

	public function scopeStatus($query, $status)
	{
		if ($status != "")
			$query->where('status', '=', "$status");
	}

	public function scopeRunner($query, $corredor)
	{
		$users = User::where('corredor', $corredor)->get();
		$query->whereIn('usuario', $users->pluck('id'));
	}

	public function scopeUser($query, $id)
	{
		if ($id != "") {
			$query->where('usuario', $id);
		}
	}

	public function scopeDateRange($query, $from, $to)
	{
		if ($from != '' && $to != '') {
			$query->whereBetween('fecha', [$from, $to]);
		}
	}

	public function scopeEnterprise($query, $id)
	{
		if ($id != "") {
			$users = User::where('enterprise', $id)->get();
			$query->whereIn('usuario', $users->pluck('id'));
		}
	}

	public function scopeGame($query, $game)
	{
		if ($game != "") {
			$games_probs = GamesProb::where('idgame', $game)->get();
			$betDetail = BetsDetail::whereIn('idgames_probs', $games_probs->pluck('id'));
			$query->whereIn('id', $betDetail->pluck('idbets'));
		}
	}

	//Methods
	public function calculeProfit()
	{
		$total = 0;

		foreach ($this->bets_detail as $key => $detail) {
			$key == 0
				? $total += $this->monto * $detail->games_probs->probabilidad
				: $total = $total * $detail->games_probs->probabilidad;
		}

		if ($this->bonus == 1) {
			$total = $total - $this->monto;
		}

		return $total;
	}
}

app/GamesProb.php
<?php

namespace App;

use App\BetsDetail;
use Illuminate\Database\Eloquent\Model;

class GamesProb extends Model
{
	protected $table = 'games_probs';

	protected $fillable = [
		'idgame', 'fecha_registro', 'tipo_probabilidad', 'equipo', 'orden', 'cantidad', 'probabilidad', 'activa',
	];

	protected $appends = [];

	public $timestamps = false;

	public function equipo()
	{
		return $this->belongsTo(Equipo::class, 'equipo')->select(array('id', 'nombre'));
	}

	public function team()
	{
		return $this->belongsTo(Equipo::class, 'equipo');
	}

	public function tipoApuesta()
	{
		return $this->belongsTo(TipoApuesta::class, 'tipo_probabilidad');
	}

	public function reglas()
	{
		return $this->belongsTo(Regla::class, 'tipo_probabilidad', 'tipo_apuesta');
	}

	public function game()
	{
		return $this->belongsTo(Game::class, 'idgame');
	}

	public function games_probs_signo()
	{
		return $this->hasOne(GamesProbsSigno::class);
	}

	public function betsDetail()
	{
		return $this->hasMany(BetsDetail::class, 'idgames_probs');
	}
	//Attributes


	public function getSelectionAttribute()
	{
		if (in_array($this->tipo_probabilidad, ['1', '8', '11', '15'])) {
			return $this->team->nombre . ' ' . $this->probabilidad;
		} else if (in_array($this->tipo_probabilidad, ['3', '7', '12', '16'])) {
			$cantidad = $this->cantidad > 0 ? $this->games_probs_signo->signo . $this->cantidad : 'PK';
			return $this->team->nombre . ' ' .  $cantidad . ' ' . $this->probabilidad;
		} else if (in_array($this->tipo_probabilidad, ['4', '10', '13', '17', '18'])) {
			$signo = $this->orden == 1 ? '+' : '-';
			return  $signo . $this->cantidad . ' ' . $this->probabilidad;
		} else if (in_array($this->tipo_probabilidad, ['6', '14'])) {
			return $this->probabilidad;
		} else if (in_array($this->tipo_probabilidad, ['9'])) {
			$siNo = $this->orden == 1 ? 'SI' : 'NO';
			return $siNo . ' ' . $this->probabilidad;
		} else if (in_array($this->tipo_probabilidad, ['19'])) {
			return $this->team->nombre;
		} else {
			return '';
		}
	}

	public function getDescriptionAttribute()
	{
		if (in_array($this->tipo_probabilidad, ['1', '3', '7', '8', '11', '12', '15', '16'])) {
			return	$this->team->nombre;
		} else if (in_array($this->tipo_probabilidad, ['4', '10', '13', '17', '18'])) {
			return $this->orden == 1 ? '+' : '-';
		} else if (in_array($this->tipo_probabilidad, ['9'])) {
			return $this->orden == 1 ? 'SI' : 'NO';
		} else {
			return '';
		}
	}
}

app/Http/Controllers/Admin/BetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bet;
use App\BetsDetail;
use App\Http\Controllers\Controller;
use App\Stsbet;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BetController extends Controller
{
	public function index(Request $request)
	{
		$status = ['' => 'Todas las apuestas'] + Stsbet::pluck('nombre', 'id')->all();

		$bets = Bet::id($request->search)
			->userName($request->search)
			->status($request->status)
			->game($request->game)
			->enterprise(Auth::user()->enterprise)
			->dateRange($request->from, $request->to)
			->orderBy('id', 'DESC')
			->with(['user', 'stsbets']);

		$jugado = 0;
		$ganancia = 0;


		if (($request->from && $request->to) || $request->game) {
			$total = $bets->get();

			$jugado = $total->whereIn('status', [1, 2, 3, 5])->sum('monto');

			$ganancia = $total->whereIn('status', [2, 5])->sum('ganancia');
		}

		$bets = $bets->paginate();

		return view('admin.bet.index', compact('bets', 'status', 'jugado', 'ganancia'));
	}

	public function show($id)
	{
		$bet = Bet::findOrFail($id);
		$betsDetail = BetsDetail::where('idbets', $id)->get()->all();
		//dd($betsDetail);
		return view('admin.bet.show', compact(['bet', 'betsDetail']));
	}

	public function update(Request $request, $id)
	{
		$bet = Bet::findOrFail($id);
		if ($bet->status != 4) {
			$bet->status = 4;
		} else {
			$bet->status = 1;
		}
		$bet->save();
		return redirect(route('admin.bet.index'));
	}

	public function balance()
	{
		//dd(request()->all());
		$status = ['' => 'Todas las apuestas'] + Stsbet::pluck('nombre', 'id')->all();
		$start = request()->start ? Carbon::parse(request()->start) :  Carbon::now();
		$end = request()->end ? Carbon::parse(request()->end) : Carbon::now();


		$bets = Bet::whereBetween('fecha_registro', [date_format($start, 'Y-m-d'), date_format($end->addDay(), 'Y-m-d')])
			->enterprise(Auth::user()->enterprise)
			->status(request()->status)
			->paginate();

		$amounts = Bet::whereBetween('fecha_registro', [date_format($start, 'Y-m-d'), date_format($end, 'Y-m-d')])
			->enterprise(Auth::user()->enterprise);

		$total = $amounts->whereNotIn('status', ['4'])->sum('monto');
		$to_pay = $amounts->whereIn('status', [2, 5])->sum('monto');

		return view('admin.bet.balance', compact('bets', 'total', 'to_pay', 'status'));
	}
}

resources/views/admin/bet/balance.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets">
	<div class="panel-heading">
	  <h5 class="text-center"><strong>Balance de Apuestas</strong></h5>
	  <div class="clearfix"></div>
	</div>
	<div class="panel-body">
		{!! Form::model(Request::all(),['route' => ['admin.bet.balance'], 'method' => 'GET', 'role' => 'search', 'class' => 'form-inline']) !!}		
			@include('partials.date', ['id' => 'start', 'selector' => 'pago-group-from', 'title' => 'Desde'])
			@include('partials.date', ['id' => 'end', 'selector' => 'pago-group-to', 'title' => 'hasta'])
			<div class="input-group">
				<label>Estatus</label>
				{!! Form::select('status', $status, null, ['class' => 'form-control']) !!}
			</div>
			<button type="submit" class="btn btn-primary btn-search" style="margin-top: 23px;">
				<span class="fa fa-search"></span> Buscar
			</button>	
		{!!  Form::close() !!}
		<div class="table-responsive">			
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Ticket</th>
						<th>Fecha</th>
						<th>Usuario</th>
						<th>Monto apostado</th>
						<th>Monto a ganar</th>
						<th>Estaus</th>	
						<th>Acciones</th>				
					</tr>
				</thead>
				<tbody>
					@foreach($bets as $bet)		
					<tr>
						<td>{{$bet->id}}</td>
						<td>{{date_format(date_create($bet->fecha_registro), 'd-m-Y h:i A')}}</td>
						<td>{{$bet->user_name}}</td>
						<td>{{number_format($bet->monto, 2)}}</td>
						<td>{{number_format($bet->ganancia,2)}}</td>
						<td>{{$bet->status_name}}</td>
						<td>					
							<a class="btn btn-default" role="button" href="{{url('owner/bet/'.$bet->id)}}"><i class="fa fa-eye" aria-hidden="true"> </i></a>
						</td>
					</tr>
					@endforeach		
				</tbody>
				<tfoot>
					<tr>
						<td colspan="2"></td>
						<th>Total vendido</th>
						<td><b>{{number_format($total, 2)}}</b></td>
						<th>A pagar</th>
						<td><b>{{number_format($to_pay, 2)}}</b></td>
					</tr>
				</tfoot>
			</table>		
		</div>
		<div class="pagination pagination-small text-center">
		{{ $bets->appends(Request::only(['start', 'end']))->render() }}
		</div>
	</div>

</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection

resources/views/admin/bet/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

		<div id="headerSeparator"></div>

		<div class="panel panel-default panel-bets">
			<div class="panel-heading">
				<h4 class="text-center">Lista de apuestas</h4>
				{!! Form::model(Request::all(),['route' => ['admin.bet.index'], 'method' => 'GET', 'role' => 'search', 'class' => 'form-inline']) !!}

				<div class="col-md-2">
					<div class="input-group">
						<label>Estatus de apuesta</label>
						{!! Form::select('status', $status, null, ['class' => 'form-control']) !!}
					</div>
				</div>
				
				<div class="col-md-2">
					@include('partials.date', ['id' => 'from', 'selector' => 'pago-group-from', 'title' => 'Desde'])		
				</div>
				<div class="col-md-2">
					@include('partials.date', ['id' => 'to', 'selector' => 'pago-group-to', 'title' => 'Hasta'])				
				</div>

				<div class="col-md-2">
					<label>Buscar por usuario o ticket</label>
					{!! Form::text('search', null, ['class' => 'form-control', 'placeholder' =>  'Buscar apuesta...', 'id'=> 'search-game']) !!}
				</div>


				<button type="submit" class="btn btn-primary btn-search" style="margin-top: 23px;">
					<span class="fa fa-search text-center"></span> Buscar
				</button>		

				{!!  Form::close() !!}

				<div class="clearfix"></div>
			</div>
			<div class="panel-body">
				<ul class="list-group col-md-8 col-md-offset-2">
					@foreach($bets as $bet)
						<li class="list-group-item">
							{{$bet->id}} - {{$bet->date}} {{$bet->userName}} 
							@if($bet->status != 4)
								Monto:<strong>{{ number_format($bet->monto, 2) }}</strong>
								A ganar: <strong>{{number_format($bet->ganancia,2) }} </strong>
							@endif
							<span class="badge {{$bet->badge}}">{{$bet->statusName}}</span>
							<div class="pull-right">
								<a class="btn btn-default" role="button" href="{{url('owner/bet/'.$bet->id)}}"><i class="fa fa-eye" aria-hidden="true"> </i></a>
							</div>
						</li>
					@endforeach
				</ul>
				<div class="clearfix"></div>

				<div class="clearfix"></div>
			</div>
			<div class="panel-footer">
				@if($jugado > 0)
					<div class="col-md-3">
						<b>Total jugado</b> {{number_format($jugado, 2)}}  			
					</div>
					<div class="col-md-3">
						<b>Total ganado</b> {{number_format($ganancia, 2)}} 			
					</div>
					<div class="col-md-3">
						<b>Utilidad</b> {{number_format($ganancia - $jugado, 2)}}
					</div>
					<div class="clearfix"></div>
				@endif
				<div class="pagination pagination-small text-center">
				{{ $bets->appends(Request::only(['search', 'role', 'from', 'to', 'game', 'status']))->render() }}
				</div>
			</div>
		</div>
		<div id="headerSeparator2"></div>
    </div>
</div>
@endsection

resources/views/admin/bet/show.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets">
	<div class="panel-heading">
	  <h5 class="text-center"><strong>#{{$bet->id}} -  {{ $bet->userName}} {{ $bet->date}}</strong></h5>
	  <div class="clearfix"></div>
	</div>
	  <div class="panel-body">
	  {!! Form::open(['route' => ['admin.bet.update', $bet], 'method' => 'PUT']) !!}
		<ul class="list-group col-md-8 col-md-offset-2">
			@foreach($betsDetail as $key => $detail)
				<li class="list-group-item" title="{{$detail->gamesProbs->idgame}}">
				{{ $detail->event}} <strong> {{$detail->betType}} - {{$detail->selection}} </strong>
				{!!$detail->tag!!}
				</li>
			@endforeach
		</ul>
		<div class="clearfix"></div>
		<br>
			<ul class="list-group col-md-8 col-md-offset-2">
				<li class="list-group-item">
					<div class="pull-left">
						<input type="submit" class="btn btn-login btn-primary btn-submit" id="btn-pago" value="{{($bet->status == 4) ? 'Reanudar' : 'Anular'}}">
						<a class="btn btn-primary btn-cancel" href="{{route(app('router')->getRoutes()->match(app('request')->create(URL::previous()))->getName())}}" role="button">Cancelar</a>
					</div>
					<div class="pull-right">
						<strong>Monto: {{ number_format($bet->monto,2) }} Ganancia: {{ number_format($bet->ganancia, 2) }}
						</strong>
					</div>
					<div class="clearfix"></div>
				</li>
			</ul>	<div class="clearfix"></div>
			<input type="hidden" name="status" value="{{ $bet->status}}">
		{!!  Form::close() !!}

  	</div>

</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection