app/Retiro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Retiro extends Model
{
	protected $fillable = ["id_usuario", "cuenta_id", "fecha", "fecha_hora", "monto", "status", "fecha_proceso", 'exchange_id',];

	public $timestamps = false;

	public function user()
	{
		return $this->belongsTo('App\User', 'id_usuario');
	}

	public function account()
	{
		return $this->belongsTo(CuentasBancaria::class, 'cuenta_id');
	}

	public function scopeId($query, $id)
	{
		if ($id != "")
			$query->where('id', $id);
	}

	public function scopeUserId($query, $users)
	{
		if (count($users) > 0) {
			$userId = [];
			foreach ($users as $user) {
				array_push($userId, $user->id);
			}
			$query->whereIn('id_usuario', $userId);
		}
	}

	//Atributes
	public function getBancoAttribute()
	{
		return $this->account ? $this->account->banco->nombre : '';
	}

	public function getAccountNumberAttribute()
	{
		return $this->account ? $this->account->nrocuenta : '';
	}
}

app/Http/Controllers/RetiroController.php
<?php

namespace App\Http\Controllers;

use Mail;
use App\User;
use App\Retiro;
use App\Exchange;
use Carbon\Carbon;
use App\Http\Requests;
use App\CuentasBancaria;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Notifications\UserWithdrawal;
use App\Notifications\AdminWithdrawal;

class RetiroController extends Controller
{
	public function store(Request $request)
	{
		$now = Carbon::now('America/Caracas');
		$now = date_format($now, "Y-m-d H:i:s");
		$user = auth()->user();
		$saldo = $user->saldo;
		$monto = $user->currency->default 
			? $request->get('monto') 
			: exchangeCurrency($request->get('monto'), $user->currency_id);
		$exchange = Exchange::where('currency_id', $user->currency_id)->latest()->first();

		if ($monto <= $saldo) {
			$retiro = Retiro::create([
				"id_usuario" => $user->id,
				"cuenta_id" => $request->get("cuenta_id"),
				"fecha" => $now,
				"fecha_hora" => $now,
				"monto" => $monto,
				"status" =>  0,
				'exchange_id' => $exchange ? $exchange->id : null,
			]);
			
			$retiro->save();
			$saldo = $retiro->user->saldo;
			$message = 'Retiro #' . $retiro->id . ' por ' . $user->currency_symbol . number_format($request->get('monto'), 2) . ' registrado exitosamente, será revisado y aprobado en breve';

			$user->notify(new UserWithdrawal($retiro));

			$admin = User::find(0);
			$admin->notify(new AdminWithdrawal($retiro));
		} else {
			$message = "El monto a retirar supera su saldo disponible";
		}

		$saldo = $user->saldo;
		return response()->json([
			'message' => $message,
			'saldo' => $saldo
		]);
	}
}

resources/views/admin/retiro/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets">
	<div class="panel-heading">
	<div class="col-md-8 col-md-offset-2">
	<h4 class="text-center">Lista de retiros</h4>	
	{!! Form::model(Request::all(),['route' => ['admin.retiro.index'], 'method' => 'GET', 'role' => 'search']) !!}
          <div class="input-group">
          	{!! Form::text('search', null, ['class' => 'form-control', 'placeholder' =>  'Buscar retiro...', 'id'=> 'name-search']) !!}
              <span class="input-group-btn">
		<button type="submit" class="btn btn-primary btn-search">  
			<span class="fa fa-search text-center"></span> Buscar                                
		</button>	
         </span>
          </div>	
	{!!  Form::close() !!}
	</div>
	<div class="clearfix"></div>
	</div>
	  <div class="panel-body">			
		<ul class="list-group col-md-8 col-md-offset-2">
			@foreach($retiros as $retiro)
				<li class="list-group-item"> 
					{{ $retiro->user->name }}  #{{ $retiro->id}} 
					<strong><i class="fa fa-money" aria-hidden="true"></i> {{ number_format($retiro->monto, 2) }}</strong>		
					@if($retiro->status == 1) 
						<span class="badge badge-success">Aprobado</span> 
					@else 
						<span class="badge">Pendiente</span> 
					@endif
					<div class="pull-right">
						<a class="btn btn-default" role="button" href="{{url('admin/retiro/'.$retiro->id)}}"><i class="fa {{ ($retiro->status == 1) ? 'fa-eye' :  'fa-check' }}" aria-hidden="true"> </i></a> 
					</div>
				</li>
			@endforeach		
		</ul>	
		<div class="clearfix"></div>
		<div class="pagination pagination-small text-center">
		{{ $retiros->appends(Request::only(['search', 'role']))->render() }}	
		</div>
		<div class="clearfix"></div>
  	</div>
</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection

resources/views/admin/retiro/show.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets"> 
	<div class="panel-heading">
	
	  <h4 class="text-center">{{ ($retiro->status == 0) ? 'Aprobar' : 'Desaptobar' }} retiro <strong>#{{$retiro->id}}</strong></h4>
	  <div class="clearfix"></div>
	</div>
	  <div class="panel-body">	
	  {!! Form::open(['route' => ['admin.retiro.update', $retiro], 'method' => 'PUT']) !!}
		<ul class="list-group col-md-8 col-md-offset-2">
			<li class="list-group-item">Numero de retiro : {{ $retiro->id }}</li>
			<li class="list-group-item">Usuario: {{ $retiro->user->name}}</li>
			<li class="list-group-item">Cédula: {{ $retiro->user->identification }}</li>
			<li class="list-group-item">Banco: {{ $retiro->banco ? $retiro->banco : '' }}</li>
			<li class="list-group-item">N° Cuenta: {{ $retiro->account_number }}</li>
			<li class="list-group-item">Fecha: {{ $retiro->fecha}}</li>
			<li class="list-group-item">Monto: {{ $retiro->monto}}</li>				
			<input type="hidden" name="status" value="{{ ($retiro->status == 0) ? '1' : '0'}}">			
			<br>
			<input type="submit" class="btn btn-login btn-primary btn-submit"  value="{{ ($retiro->status == 0) ? 'Aprobar' : 'Desaprobar' }}">	
			<a class="btn btn-primary btn-cancel" href="/admin/retiro" role="button">Cancelar</a>
		</ul>
		{!!  Form::close() !!}
  	</div>
  	<div class="clearfix"></div>
</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection