app/User.php
<?php

namespace App;

use App\BetsDetail;
use App\CuentasBancaria;
use App\Notifications\MyResetPassword;
use Carbon\Carbon;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
	use Notifiable;

	protected $fillable = [
		'name', 'email', 'password', 'identification', 'birth_date', 'phone', 'status', 'logro', 'enterprise', 'printer', 'corredor', 'role', 'currency_id'
	];

	protected $hidden = [
		'password', 'remember_token',
	];

	protected $appends = [
		'first_name', //'currency_symbol', 'saldo', 'bonus', 
	];

	//Relationships

	public function pagos()
	{
		return $this->hasMany(Pago::class, 'id_usuario');
	}

	public function retiros()
	{
		return $this->hasMany(Retiro::class, 'id_usuario');
	}
	public function bets()
	{
		return $this->hasMany(Bet::class, 'usuario');
	}

	public function corredorComision()
	{
		return $this->hasOne(CorredorComision::class, 'idusuario');
	}

	public function accounts()
	{
		return $this->hasMany(CuentasBancaria::class);
	}

	public function empresa()
	{
		return $this->belongsTo(Empresa::class, 'enterprise');
	}

	public function secrets()
	{
		return $this->hasMany(Secret::class);
	}

	public function coupons()
	{
		return $this->hasMany(Coupon::class);
	}

	public function currency() 
	{
		return $this->belongsTo(Currency::class);
	}

	//Attributes

	public function getSaldoAttribute()
	{
		$balance = $this->payApproved + $this->bets_win - ($this->bet_sum + $this->retiros->sum('monto'));
		
		// if ($this->currency && !$this->currency->default) {			
		// 	$balance = exchangeDefault($balance, $this->currency_id);
		// }
		
		return $balance;
	}

	public function getBetSumAttribute()
	{
		return $this->bets->where('bonus', 0)->sum('monto') - $this->bets->where('status', 4)->sum('monto');
	}

	public function getArriesgadoAttribute()
	{
		$arriesgado = number_format($this->bets()->where('status', '1')->sum('monto'), 2);
		return $arriesgado;
	}

	public function getTipoComisionAttribute()
	{
		return isset($this->corredorComision) ? $this->corredorComision->idtipo_comision : '';
	}

	public function getBetsWinAttribute()
	{
		$sum = DB::table('bets')->where('usuario', $this->id)->where('status', 2)->sum('ganancia');
		return $sum;
	}

	public function getPayApprovedAttribute()
	{
		return $this->pagos->whereIn('status', ['1', 1])->sum('monto');
	}

	public function getSellsAttribute()
	{
		return isset($this->corredorComision) ? $this->corredorComision->ventas : '';
	}

	public function getBankAccountAttribute()
	{
		return isset($this->corredorComision) ? $this->corredorComision->ventas : '';
	}

	public function getAccountNumberAttribute()
	{
		return isset($this->accounts->first()->nrocuenta) ? $this->accounts->first()->nrocuenta : '';
	}

	public function getAccountsAttribute()
	{
		return isset($this->accounts) ? $this->accounts() : [];
	}

	public function getBankAttribute()
	{
		return isset($this->accounts->first()->banco->nombre) ? $this->accounts->first()->banco->nombre : '';
	}

	public function getFirstNameAttribute()
	{
		$pos = strpos($this->name, ' ');

		if (! $pos) {
			return $this->name;
		}

		return substr($this->name, 0, $pos);
	}
	
	public function getBonusAttribute()
	{
		if (! $this->has('coupons')) {
			return null;
		}
		
		$coupons = $this->coupons;
		$sum = $coupons->sum('amount');
		$bets = $this->bets->where('bonus', 1)->sum('monto');
		$total = $sum - $bets;

		// if ($this->currency && !$this->currency->default) {
		// 	$total = exchangeDefault($total, $this->currency_id);
		// }

		return $total;
	}

	public function getCurrencySymbolAttribute()
	{
		// $currency = Currency::find($this->currency_id);
		// if ($currency && $currency->symbol) {
		// 	return $currency->symbol;
		// }

		return '';
	}

	//Scopes

	public function scopeName($query, $name)
	{
		if ($name != "")
			$query->where('name', 'LIKE', "%$name%");
	}

	//Methods
	public function sendPasswordResetNotification($token)
	{
		$this->notify(new MyResetPassword($token));
	}

	public function IsAdmin()
	{
		return $this->role == 'admin';
	}

	public function isOwner()
	{
		return in_array($this->role, ['admin', 'owner']);
	}

	public function team_acum($games_probs)
	{
		$amount = 0;
		$betsDetail = BetsDetail::where('idgames_probs', $games_probs)->get();
		foreach ($betsDetail as $detail) {
			$amount += Bet::where(['usuario' => auth()->user()->id, 'id' => $detail->idbets])->sum('monto');
		}

		return $amount;
	}

	public function fixBalance()
	{
		$start = Carbon::now();
		foreach ($this->bets as $bet) {
			$bet->ganancia = $bet->calculeProfit();
			$bet->save();
		}
		$end = Carbon::now()->diffForHumans($start);
		echo "User #{$this->id} actualizado $end \n";
		return '';
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\User;
use App\TipoComision;
use App\CorredorComision;
use App\Empresa;

class UserController extends Controller
{
	public function index(Request $request)
	{
		$users = User::name($request->name)
			->where('status', 1)
			->paginate();

		return view('admin.user.index', compact('users'));
	}

	public function show($id)
	{
		$tipoComisiones = ['' => 'Seleccione el tipo de comision'] + TipoComision::pluck('nombre', 'id')->all();
		$empresas = ['' => 'Seleccione la empresa'] + Empresa::pluck('nombre', 'id')->all();
		$user = User::findOrFail($id);
		return view('admin.user.show', compact('user', 'tipoComisiones', 'empresas'));
	}

	public function update(Request $request, $id)
	{
		if ($request->corredor == 1) {
			$this->validate($request, [
				'tipoComision' => 'required',
				'ventas' => 'required'
			]);
		}
		$user  = User::findOrFail($id);
		$user->fill($request->all());
		$user->save();

		$corredorComisiones = CorredorComision::where('idusuario', $user->id)->get();

		if ($corredorComisiones->count() > 0) {
			foreach ($corredorComisiones as $comision) {
				$comision->delete();
			}
		}

		if ($request->corredor == 1) {
			CorredorComision::create([
				'idusuario' => $user->id,
				'idtipo_comision' => $request->tipoComision,
				'ventas' => $request->ventas,
			]);
		}


		return redirect('/admin/user');
	}
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
	public function checkMail()
	{
		$user = User::where('email', request()->email)->first();

		$message = $user ? 'El correo ingresado ya se encuentra en nuestra Base de datos' : 'valid';

		return [
			'message' => $message,
		];
	}

	public function balance()
	{
		$data = [
			'balance' => auth()->user()->saldo,
			'bonus' => auth()->user()->bonus,
			'currency_symbol' => auth()->user()->currency_symbol,
		];
		return $data;
	}
}

resources/views/admin/user/index.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets">
	<div class="panel-heading">
	<div class="col-md-8 col-md-offset-2">
	<h4 class="text-center">Lista de usuarios</h4>	
	{!! Form::model(Request::all(),['route' => ['admin.user.index'], 'method' => 'GET', 'role' => 'search']) !!}
          <div class="input-group">
          	{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' =>  'Buscar usuario...', 'id'=> 'name-search']) !!}
              <span class="input-group-btn">
		<button type="submit" class="btn btn-primary btn-search">  
			<span class="fa fa-search"></span> Buscar                                
		</button>	
         </span>
          </div>	
	{!!  Form::close() !!}
	</div>
	<div class="clearfix"></div>
	</div>
	  <div class="panel-body">			
		<ul class="list-group col-md-8 col-md-offset-2">
			@foreach($users as $user)
				<li class="list-group-item"> 
					{{$user->id}} - {{$user->name}} 
						@if($user->corredor == 0)
						<strong><i class="fa fa-money" aria-hidden="true"></i> {{ number_format($user->saldo, 2) }}</strong>
						@endif
					<div class="pull-right">
						<a class="btn btn-default" role="button" href="{{url('admin/user/'.$user->id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
					</div>
				</li>
			@endforeach		
		</ul>	
		<div class="clearfix"></div>
		<div class="pagination pagination-small text-center">
		{{ $users->appends(Request::only(['name', 'role']))->render() }}	
		</div>
		<div class="clearfix"></div>
  	</div>
</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app')
@section('content')

<div class="row-fluid">
    <div class="span12">

        <div id="headerSeparator"></div>

<div class="panel panel-default panel-bets">
	<div class="panel-heading">
	  <div class="pull-left">Editar usuario #{{$user->id}} <strong>{{$user->name}}</strong></div>
		@if($user->corredor == 0)
			  <div class="pull-right"><strong><i class="fa fa-money" aria-hidden="true"></i> {{ number_format($user->saldo, 2) }}</strong></div>		
		@endif
	  <div class="clearfix"></div> 
	</div>
	  <div class="panel-body">		
	  {!! Form::open(['route' => ['admin.user.update', $user], 'method' => 'PUT']) !!}	  
		<ul class="list-group col-md-8 col-md-offset-2">
			{!! Alert::render() !!}
			{!! Field::text('name', $user->name) !!}
			{!! Field::text('email', $user->email) !!}
			{!! Field::text('phone', $user->phone) !!}			
			{!! Field::select('status', ['empty' => 'Seleccione', '0' => 'Inactivo', '1' => 'Activo' ], $user->status) !!}
			{!! Field::select('printer', ['1' => 'POS 58 Termica', '2' => 'EPSON TM-U325 (MATRIZ DE PUNTO)', ], $user->printer) !!}
			{!! Field::select('corredor', ['0' => 'No', '1' => 'Si', ], $user->corredor) !!}
			<ul id="corredor-comision" class="{{($user->corredor == '0') ? 'hidden' : ''}}">
				<li class="list-group-item">
					<div class="form-group">
		    			{!! Form::label('tipoComision', 'Tipo de comision') !!}
					{!! Form::select('tipoComision', $tipoComisiones,  $user->tipoComision , ['class' => 'form-control', 'onChange' => 'enableButton()']) !!}	
					</div>
					<div class="form-group">
		    			{!! Form::label('ventas', 'Calculo en base a') !!}
					{!! Form::select('ventas', ['' => 'Seleccione tipo de calculo', '0' => 'Ganancias', '1' => 'Ventas'],  $user->sells , ['class' => 'form-control', 'onChange' => 'enableButton()']) !!}	
					</div>										
				</li>			
			</ul>
			<br>
			{!! Field::select('role', ['user' => 'Usuario', 'owner' => 'Propietario', 'admin' => 'Administrador', ], $user->role, ['label' => 'Tipo de usuario']) !!}
			@if($user->accounts->count() > 0)
				<label>Cuentas Bancarias</label>
				@foreach($user->accounts as $account)
					<p class="text-uppercase"> {{$account->tipo . ' ' . $account->banco->nombre . $account->nrocuenta}}</p>
				@endforeach
			@endif
			{!! Field::select('enterprise', $empresas, $user->enterprise, ['label' => 'Empresa']) !!}
			<br>
			<input type="submit" class="btn btn-login btn-primary btn-submit" id="btn-update-user" value="Enviar">	
			<a class="btn btn-primary btn-cancel" href="/admin/user" role="button">Cancelar</a>
		</ul>
		{!!  Form::close() !!}
  	</div>
  	<div class="clearfix"></div>
</div>
        <div id="headerSeparator2"></div>
    </div>
</div>
@endsection